### ISSUE TITLE
Question about the datasets which are used by proxcocoa

### ISSUE THREAD

**Issue by codlife** [gingsmith/proxcocoa#4]
Hi @gingsmith 
   From your paper Communication-Efficient Distributed Dual Coordinate Ascent, I see in the part of experiment, you use rcv1 to test cocoa, I find that rcv1 dataset is a multi-class problems, and the same record maybe belong to many classes. so what trouble me is how you process this? thank you!

**Comment by gingsmith** [comment]
Hi @codlife, thanks for your question -- we used the rcv1 dataset from the libsvm repository: https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary.html, where they bin the groups together to form a binary classification problem (with CCAT, ECAT as positive, and GCAT, MCAT as negative).

**Comment by codlife** [comment]
Thank you very much! @gingsmith
